name: Build and Test API / Build Docker image and push to Docker Hub
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "CleanArchiStarterTemplate/**" ## Change this or remove it, needed because of the template

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .ET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build with dotnet
        working-directory: ./CleanArchiStarterTemplate
        run: dotnet build --configuration Release

      - name: Run tests with dotnet
        working-directory: ./CleanArchiStarterTemplate
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./CleanArchiStarterTemplate
          file: ./CleanArchiStarterTemplate/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/starter-app:latest
